### ISSUE TITLE
Invalid Stripe key

### ISSUE THREAD

**Issue by cassidyjames** [matthiasjg/trimirjournal#5]
I'm not sure where this Stripe key came from, but it appears to be failing to process payments in AppCenter:

https://github.com/matthiasjg/trimirjournal/blob/417007f9cf6722cc4e0e69c19c84c93ba93ad66f/data/trimir-journal.appdata.xml.in#L104

**Comment by matthiasjg** [comment]
Thx @cassidyjames for submitting the issue.

I've already noticed, that paying for the app doesn't work. But I thought it might be a general eos 6/ app center issue that is being worked on (based on a my research at the time, if I recall correctly).

Anyways, the key ended there based on my understanding of reading https://docs.elementary.io/develop/writing-apps/our-first-app#appdata.xml

So, at the time, I might very well have totally misread/ understood the paragraph b/c it's now clearly saying:

> Developers of new apps will receive their key in the new AppCenter Dashboard once it is live. :thinking: 

The current key is from my Stripe account b/c I thought that is being used by elementary to then transfer the developers share of any payment. Well, it seems a totally false assumption of mine, sorry :-/ 

So, how am I then supposed to receive a key? Could you help me w/ this? Your help would be greatly appreciated.
